from __future__ import annotations

"""Stable import surface for the application's PostgreSQL-backed state store.

backend/api/* and backend/researcher_crew import conversation/admin/FAQ/
semantic-cache/activity-log functions from here; the implementation lives in
backend/db/repository.py (SQLAlchemy).
"""

from backend.db.repository import (
    DEFAULT_GUARDRAILS_RULES,
    add_admin_by_email,
    append_conversation_turn,
    clear_semantic_cache,
    create_conversation,
    delete_activity_log,
    delete_activity_logs_for_conversation,
    delete_conversation,
    get_session_signing_secret,
    get_conversation_context,
    get_conversation_messages,
    get_conversation_owner,
    get_guardrails_rules,
    get_semantic_cache_entry,
    get_semantic_cache_entry_by_question,
    get_user_by_email,
    init_state_db,
    insert_activity_log,
    insert_semantic_cache_entry,
    list_activity_log_sessions,
    list_activity_logs,
    list_conversations_for_user,
    list_faq_items,
    mark_activity_log_cached,
    mark_semantic_cache_hit,
    normalize_semantic_question,
    rename_conversation,
    replace_faq_items,
    set_guardrails_rules,
    state_counts,
    summarize_activity_logs,
    touch_conversation,
    update_activity_log_feedback,
    upsert_user,
)

__all__ = [
    "DEFAULT_GUARDRAILS_RULES",
    "add_admin_by_email",
    "append_conversation_turn",
    "clear_semantic_cache",
    "create_conversation",
    "delete_activity_log",
    "delete_activity_logs_for_conversation",
    "delete_conversation",
    "get_admin_session_secret",
    "get_conversation_context",
    "get_conversation_messages",
    "get_conversation_owner",
    "get_guardrails_rules",
    "get_semantic_cache_entry",
    "get_semantic_cache_entry_by_question",
    "get_user_by_email",
    "init_state_db",
    "insert_activity_log",
    "insert_semantic_cache_entry",
    "is_admin_email",
    "list_activity_log_sessions",
    "list_activity_logs",
    "list_conversations_for_user",
    "list_faq_items",
    "mark_activity_log_cached",
    "mark_semantic_cache_hit",
    "normalize_semantic_question",
    "rename_conversation",
    "replace_faq_items",
    "set_guardrails_rules",
    "state_counts",
    "summarize_activity_logs",
    "touch_conversation",
    "update_activity_log_feedback",
    "upsert_user",
]
